GRANT SELECT ON M_NPB_TEAM_LIST TO SCOTT;
GRANT SELECT ON M_NPB_POSITION TO SCOTT;
GRANT SELECT ON T_NPB_PLAYER_LIST TO SCOTT;
GRANT INSERT ON T_NPB_PLAYER_LIST TO SCOTT;
GRANT UPDATE ON T_NPB_PLAYER_LIST TO SCOTT;
GRANT DELETE ON T_NPB_PLAYER_LIST TO SCOTT;

